### PR TITLE
Remove avatar

### PR DESCRIPTION
**Pull request by henrikstranneheim**
### Added

-

### Changed

- Remove Avatar from user table and code as it is not used

### Fixed

-

### How to prepare for test
- [ ] ssh to hasta (depending on type of change)
- [ ] activate stage: `us`
- [ ] request trailblazer-stage on hasta: `paxa`
- [ ] install on stage:
    ```Shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_trailblazer -t trailblazer -b remove-avatar -a
    ```
- [ ] ssh to clinical-db (depending on type of change)
- [ ] install on stage:
`bash /home/proj/production/servers/resources/clinical-db.scilifelab.se/update-trailblazer-ui-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [ ] login to ...
- [ ] do ...

### Expected test outcome
- [ ] check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by henrikstranneheim** [comment]
### CLI and API 👍 
```
θ60° [henrik.stranneheim@hasta:~] [S_base] 2m47s $ trailblazer scan
Error updating analysis for: case - grandaphid : [Errno 13] Permission denied: '/home/proj/production/cancer/cases/grandaphid/analysis/slurm_jobids.yaml'
Error updating analysis for: case - goodbengal : [Errno 2] No such file or directory: '/home/proj/production/nipt/cases/goodbengal/output/sacct/submitted_jobs.yaml'
Error updating analysis for: case - helpedlab : [Errno 2] No such file or directory: '/home/proj/production/nipt/cases/helpedlab/output/sacct/submitted_jobs.yaml'
Error updating analysis for: case - newgopher : [Errno 13] Permission denied: '/home/proj/production/microbial/results/reports/trailblazer/ACC9662_slurm_ids.yaml'
Error updating analysis for: case - onestag : [Errno 13] Permission denied: '/home/proj/production/microbial/results/reports/trailblazer/ACC9966_slurm_ids.yaml'
Error updating analysis for: case - funnyaphid : [Errno 2] No such file or directory: '/home/proj/production/mutant/cases/funnyaphid/results/trailblazer_config.yaml'
Error updating analysis for: case - proudfish : [Errno 13] Permission denied: '/home/proj/production/microbial/results/reports/trailblazer/ACC9337_slurm_ids.yaml'
Error updating analysis for: case - setcolt : [Errno 13] Permission denied: '/home/proj/production/microbial/results/reports/trailblazer/ACC9963_slurm_ids.yaml'
Error updating analysis for: case - handyshrimp : [Errno 2] No such file or directory: '/home/proj/production/mutant/cases/handyshrimp/results/trailblazer_config.yaml'
Error updating analysis for: case - divinetomcat : [Errno 13] Permission denied: '/home/proj/production/microbial/results/reports/trailblazer/ACC5119_slurm_ids.yaml'
Error updating analysis for: case - HW2V2DRX2 : [Errno 2] No such file or directory: '/home/proj/production/flowcells/novaseq/runs/230504_A00689_0805_AHW2V2DRX2/slurm_job_ids.yaml'
Error updating analysis for: case - savingstag : [Errno 2] No such file or directory: '/home/proj/production/mutant/cases/savingstag/results/trailblazer_config.yaml'
Error updating analysis for: case - topewe : [Errno 13] Permission denied: '/home/proj/production/microbial/results/reports/trailblazer/ACC12566_slurm_ids.yaml'
Error updating analysis for: case - fullgoat : [Errno 13] Permission denied: '/home/proj/production/microbial/results/reports/trailblazer/ACC12567_slurm_ids.yaml'
Status in Tower: coolkodiak - 282044 - WPjrjs23yxQwq
Error logging case - coolkodiak :  JSONDecodeError
Updated status wondrousbaboon - 287260: failed
Updated status upkangaroo - 287264: completed
Updated status balancedjackass - 287373: completed
Updated status trustingviper - 287374: completed
Updated status factualsilkworm - 287375: completed
Updated status drivingbedbug - 287376: completed
Updated status directpika - 287378: completed
Updated status workingpython - 287380: completed
Status in Tower: harmlessglider - 287387 - 40stB3IsypVWov
Error logging case - harmlessglider :  JSONDecodeError
Status in Tower: adaptingvervet - 287388 - 3NcuEyaWfTxaLY
Error logging case - adaptingvervet :  JSONDecodeError
Status in Tower: helpingox - 287389 - 18MLl0Me3WREgi
Error logging case - helpingox :  JSONDecodeError
Status in Tower: workableoarfish - 287390 - 37sDYfoMlWiVt
Error logging case - workableoarfish :  JSONDecodeError
Status in Tower: stirreddragon - 287391 - 58FxBODijVbbb2
Error logging case - stirreddragon :  JSONDecodeError
Status in Tower: steadygoose - 287392 - 1q33XhNRVm6ZQ
Error logging case - steadygoose :  JSONDecodeError
Status in Tower: alertparakeet - 287393 - 1XzACZoQkwShgC
Error logging case - alertparakeet :  JSONDecodeError
Updated status cunningwalrus - 287401: running
Updated status winningpig - 287402: running
All analyses updated!
```

Screenshot 2024-01-26 at 15 16 39

**Review by diitaz93 — APPROVED** [review]
Looks good 👍 But what was the avatar?

**Comment by henrikstranneheim** [comment]
Deployed to production:
```
Log deploy... done.
trailblazer, version 20.2.4
```

**Comment by henrikstranneheim** [comment]
> Looks good 👍 But what was the avatar?

It was a failed rouge project by a former colleague.

**Pull request merged**
