### PR TITLE
reinstate old deploy to pypi

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
This PR adds deploy to pypi

### How to test Travis config
- [x] open this PR

### Expected test outcome
- [x] check that it builds on travis

### How to test deploy to pypi
- [x] bump a patch tag to this branch
- [x] open the travis build details 

### Expected test outcome
- [x] check that it mentions deploying to pypi
- [x] check that pypi has a deploy with the new release

- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by HS
- [x] tests executed by PG
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by henrikstranneheim — APPROVED** [review]
👍

**Comment by patrikgrenfeldt** [comment]
Test deploy to pypi: 
image
👍 
image
👍

**Comment by patrikgrenfeldt** [comment]
@henrikstranneheim Can we M&D this?

**Review by henrikstranneheim — APPROVED** [review]
👍

**Pull request merged**
