### PR TITLE
feat(rm_cli_check): As it is not used and TB should not do this as MI…

### PR DESCRIPTION
**Pull request by henrikstranneheim**
This PR adds/fixes:
- As it is not used and TB should not do this as MIP does it better

### How to prepare for test
- [x] ssh to hasta
- [x] activate stage: `us`
- [x] request trailblazer-stage on hasta: `paxa`
- [x] install on stage:
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-trailblazer-stage.sh rm_trailblazer_check`

### How to test
- [x] login to hasta
- [x] do `us`
1. `trailblazer scan` ✅ 
1. `trailblazer ls` ✅ 
1. `trailblazer cancel` ✅ 
1. `trailblazer delete` ✅ 

### Expected test outcome
- [x] check that the commands work without errrors
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by PG
- [x] tests executed by HS
- [x] "Merge and deploy" approved by PG
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner (no code using this functionality found, no human users are currently utilising this feature)
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by henrikstranneheim** [comment]
### How to test
- [ ] login to hasta
- [ ] do `us`
1. `trailblazer scan`
Screenshot 2020-08-20 at 09 37 16

1. `trailblazer ls`
Screenshot 2020-08-20 at 09 46 53

1. `trailblazer cancel 219395`
Screenshot 2020-08-20 at 09 47 35

1. `trailblazer delete 219390`
Screenshot 2020-08-20 at 09 45 14


### Expected test outcome
- [ ] check that the commands work without errrors
- [ ] Take a screenshot and attach or copy/paste the output.

**Review by jemten — APPROVED** [review]
👍

**Review by karlnyr — APPROVED** [review]
Completely redundant code. Looks good to me!

**Comment by henrikstranneheim** [comment]
Deployed on Hasta:
Screenshot 2020-08-25 at 08 08 29

**Pull request merged**
