### PR TITLE
feat(imports): Rm generic model import

### PR DESCRIPTION
**Pull request by henrikstranneheim**
## Description

Remove generic model import

### Changed

- Rm generic model import

### How to prepare for test
- [ ] ssh to hasta (depending on type of change)
- [ ] activate stage: `us`
- [ ] request trailblazer-stage on hasta: `paxa`
- [ ] install on stage:
    ```Shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_trailblazer -t trailblazer -b rm_models_import -a
    ```
- [ ] ssh to clinical-db (depending on type of change)
- [ ] install on stage:
`bash /home/proj/production/servers/resources/clinical-db.scilifelab.se/update-trailblazer-ui-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [ ] login to ...
- [ ] do ...

### Expected test outcome
- [ ] check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by seallard — APPROVED** [review]
Nice 👍

**Comment by henrikstranneheim** [comment]
Will ignore code smells for now and address them in future PRs when we deprecate Alchy

**Comment by henrikstranneheim** [comment]
### trailblazer  update-analysis 271866 ✅ 
```
θ65° [henrik.stranneheim@hasta:~] [S_base] 1m48s $ trailblazer  update-analysis 271866
Status in SLURM: civilsole - 271866
         id                                         step     status  time_limit  time_elapsed              started
0   4798531                               vep_somatic_sv  COMPLETED    12:00:00            27  2023-06-03T21:24:38
1   4798526                     vep_somatic_clinical_snv  COMPLETED    18:00:00             1  2023-06-03T21:20:51
2   4798524                     vep_somatic_research_snv  COMPLETED    18:00:00            43  2023-06-03T20:37:45
3   4798512                            sentieon_DNAscope  COMPLETED  1-00:00:00            18  2023-06-03T19:43:16
4   4798515                  sentieon_TNscope_tumor_only  COMPLETED  1-00:00:00            52  2023-06-03T19:43:16
5   4798510                    sentieon_base_calibration  COMPLETED  1-00:00:00            14  2023-06-03T19:28:45
6   4798506                               mergeBam_tumor  COMPLETED  1-06:00:00           313  2023-06-03T14:15:09
7   4798504                             sentieon_realign  COMPLETED  1-00:00:00             7  2023-06-03T14:07:16
8   4798501                               sentieon_dedup  COMPLETED  1-00:00:00             7  2023-06-03T13:59:21
9   4798500                          sentieon_align_sort  COMPLETED  1-00:00:00            84  2023-06-03T12:34:55
10  4798535                  bcftools_filter_sv_clinical  COMPLETED    12:00:00             1  2023-06-03T21:56:10
11  4798533     annotate_clinical_observation_somatic_sv  COMPLETED    12:00:00             1  2023-06-03T21:54:20
12  4798534                  bcftools_filter_sv_research  COMPLETED    12:00:00             1  2023-06-03T21:54:20
13  4798532         annotate_swegen_frequency_somatic_sv  COMPLETED    12:00:00             2  2023-06-03T21:52:02
14  4798527                 bcftools_quality_filter_svdb  COMPLETED    12:00:00             0  2023-06-03T21:24:35
15  4798520              vcf2cytosure_convert_tumor_only  COMPLETED    12:00:00             0  2023-06-03T21:24:09
16  4798525                        svdb_merge_tumor_only  COMPLETED     2:00:00             0  2023-06-03T21:24:09
17  4798517                      bcftools_process_SV_CNV  COMPLETED     1:00:00             0  2023-06-03T21:24:05
18  4798530  bcftools_filter_tnscope_clinical_tumor_only  COMPLETED     3:00:00             0  2023-06-03T21:21:56
19  4798528                              tmb_calculation  COMPLETED    12:00:00            25  2023-06-03T21:20:51
20  4798529  bcftools_filter_tnscope_research_tumor_only  COMPLETED     4:00:00             1  2023-06-03T21:20:51
21  4798521   bcftools_quality_filter_tnscope_tumor_only  COMPLETED    12:00:00             0  2023-06-03T20:37:05
22  4798522                          cnvpytor_tumor_only  COMPLETED     5:00:00            27  2023-06-03T20:37:05
23  4798519                  bcftools_view_split_variant  COMPLETED    12:00:00             1  2023-06-03T20:35:55
24  4798513                         delly_cnv_tumor_only  COMPLETED    12:00:00            52  2023-06-03T20:31:33
25  4798518                           vep_germline_tumor  COMPLETED    12:00:00            71  2023-06-03T20:01:40
26  4798516                                      multiqc  COMPLETED       15:00             0  2023-06-03T19:43:16
27  4798514                           vep_germline_tumor  COMPLETED    12:00:00            15  2023-06-03T19:42:41
28  4798507                          delly_sv_tumor_only  COMPLETED    12:00:00            62  2023-06-03T19:28:45
29  4798508                         tiddit_sv_tumor_only  COMPLETED    10:00:00            45  2023-06-03T19:28:45
30  4798509                               manta_germline  COMPLETED     5:00:00            13  2023-06-03T19:28:45
31  4798511                             manta_tumor_only  COMPLETED    10:00:00            15  2023-06-03T19:28:45
32  4798502                     picard_CollectWgsMetrics  COMPLETED    12:00:00           127  2023-06-03T14:07:16
33  4798503                         sentieon_wgs_metrics  COMPLETED    12:00:00            35  2023-06-03T14:07:16
34  4798505                picard_CollectMultipleMetrics  COMPLETED    12:00:00            75  2023-06-03T14:07:16
35  4798499                                        fastp  COMPLETED    12:00:00            22  2023-06-03T12:12:22
36  4798497                                    fastp_umi  COMPLETED  1-00:00:00            27  2023-06-03T11:44:30
37  4798498                                       fastqc  COMPLETED    12:00:00            92  2023-06-03T11:44:30
38  4798536                    collect_custom_qc_metrics  COMPLETED       15:00             0  2023-06-03T21:57:56
39  4798523                                   cnv_report  COMPLETED       15:00             0  2023-06-03T21:04:37
40  4798537                                          all     FAILED       15:00             0  2023-06-03T21:58:01
Updated status civilsole - 271866: failed
```

**Comment by henrikstranneheim** [comment]
Deployed on Hasta:

```
Log deploy... done.
trailblazer, version 12.0.7
θ65° [henrik.stranneheim@hasta:~] [P_base] 1m17s $
```

**Pull request merged**
