### PR TITLE
Get analysis

### PR DESCRIPTION
**Pull request by henrikstranneheim**
This PR adds/fixes:

- Renamed "is_running" to "is_ongoing" to reflect that ongoing also mean "pending" in addition to "running"
- Added is_failed status and def
- Added is_completed status and def
- Added tests

### How to prepare for test
- [x] ssh to hasta
- [x] activate stage: `us`
- [x] request trailblazer-stage on hasta: `paxa`
- [x] install on stage:
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-trailblazer-stage.sh get_analysis`

### How to test
- [x] login to hasta
- [x] do `us`
1. `trailblazer ls`
1. `trailblazer delete coolsole`

### Expected test outcome
1. check that the cases are listed ✅ 
1. check that the case is deleted ✅ 

- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [x] code approved by PG
- [x] tests executed by HS
- [x] "Merge and deploy" approved by AJ
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

**Implementation plan**
- [ ] Merge together with PR: https://github.com/Clinical-Genomics/cg/pull/717

### CODE REVIEW

**Comment by henrikstranneheim** [comment]
@henningonsbring @patrikgrenfeldt Could you have a look at this to solve the probblem with cases that start for completed analysis as well.

**Comment by henrikstranneheim** [comment]
### How to test
- [x] login to hasta
- [x] do `us`
1. `trailblazer ls`
Screenshot 2020-08-25 at 15 57 29

1. `trailblazer delete flyinghermit`
Screenshot 2020-08-25 at 15 58 45
Screenshot 2020-08-25 at 15 59 09

### Expected test outcome
1. check that the cases are listed ✅ 
1. check that the case is deleted ✅

**Review by patrikgrenfeldt — APPROVED** [review]
👍

**Review by jemten — APPROVED** [review]
👍

**Comment by patrikgrenfeldt** [comment]
Deployed on Hasta:
image

**Pull request merged**
