### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by henrikstranneheim**
This PR adds/fixes:

- Updates code-owners

## Review
- [x] code approved by MR
- [x] "Merge and deploy" approved by MR
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by henrikstranneheim** [comment]
@elevu Adding you as a code-owner to TB. I hope this is okej?

**Comment by elevu** [comment]
sure 👍

**Review by Mropat — APPROVED** [review]
👍

**Comment by Mropat** [comment]
Welcome @elevu 🥳

**Comment by Mropat** [comment]
@henrikstranneheim also do not forget to set group admin - bumpversion is not possible to do without this!

**Comment by henrikstranneheim** [comment]
@Mropat Setting to admin - done!

**Pull request merged**
