### PR TITLE
fix(alembic):

### PR DESCRIPTION
**Pull request by henrikstranneheim**
### Added

-

### Changed

-

### Fixed

- Alembic revision

### How to prepare for test
- [ ] ssh to hasta (depending on type of change)
- [ ] activate stage: `us`
- [ ] request trailblazer-stage on hasta: `paxa`
- [ ] install on stage:
    ```Shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_trailblazer -t trailblazer -b fix-alembic-migration-a
    ```
- [ ] ssh to clinical-db (depending on type of change)
- [ ] install on stage:
`bash /home/proj/production/servers/resources/clinical-db.scilifelab.se/update-trailblazer-ui-stage.sh fix-alembic-migration`

### How to test
- [ ] login to ...
- [ ] do ...

### Expected test outcome
- [ ] check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by islean — COMMENTED** [review]
Pretty certain that you will need to remove the other revision (2024_01_19_bebe0db0c8de_rename_sars_cov_2_to_mutant.py) with the same logic, since its revisions are not compatible, in order to fix the deployments

**Comment by henrikstranneheim** [comment]
In this PR?

**Review by islean — APPROVED** [review]
Looks good! 🔥

**Comment by henrikstranneheim** [comment]
```
θ62° [henrik.stranneheim@hasta:~] [S_base] 3s $ bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_trailblazer -t trailblazer -b fix-alembic-migration -a
Collecting git+https://github.com/Clinical-Genomics/trailblazer@fix-alembic-migration
  Cloning https://github.com/Clinical-Genomics/trailblazer (to revision fix-alembic-migration) to ./tmp/pip-req-build-yjd4zwjm
  Running command git clone --quiet https://github.com/Clinical-Genomics/trailblazer /home/henrik.stranneheim/tmp/pip-req-build-yjd4zwjm
  Running command git checkout -b fix-alembic-migration --track origin/fix-alembic-migration
  Switched to a new branch 'fix-alembic-migration'
  Branch fix-alembic-migration set up to track remote branch fix-alembic-migration from origin.
  Resolved https://github.com/Clinical-Genomics/trailblazer to commit ab021b808b3770346c1044d2093a6a592290514e
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: trailblazer
  Building wheel for trailblazer (pyproject.toml) ... done
  Created wheel for trailblazer: filename=trailblazer-20.2.5-py3-none-any.whl size=45719 sha256=e826facd48f52a9f87da1446c014b65e170dad74370b003abe336c10785b2680
  Stored in directory: /home/henrik.stranneheim/tmp/pip-ephem-wheel-cache-5lx2nu_j/wheels/69/d4/fb/6dda2d0f006ff32d0c7077a42c3100621a592d13dd2aa05d34
Successfully built trailblazer
Installing collected packages: trailblazer
  Attempting uninstall: trailblazer
    Found existing installation: trailblazer 20.2.5
    Uninstalling trailblazer-20.2.5:
      Successfully uninstalled trailblazer-20.2.5
Successfully installed trailblazer-20.2.5
Collecting git+https://github.com/Clinical-Genomics/trailblazer@fix-alembic-migration
  Cloning https://github.com/Clinical-Genomics/trailblazer (to revision fix-alembic-migration) to ./tmp/pip-req-build-_ceoyi52
  Running command git clone --quiet https://github.com/Clinical-Genomics/trailblazer /home/henrik.stranneheim/tmp/pip-req-build-_ceoyi52
  Running command git checkout -b fix-alembic-migration --track origin/fix-alembic-migration
  Switched to a new branch 'fix-alembic-migration'
  Branch fix-alembic-migration set up to track remote branch fix-alembic-migration from origin.
  Resolved https://github.com/Clinical-Genomics/trailblazer to commit ab021b808b3770346c1044d2093a6a592290514e
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: Click in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from trailblazer==20.2.5) (8.1.7)
Requirement already satisfied: SQLAlchemy in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from trailblazer==20.2.5) (2.0.23)
Requirement already satisfied: alembic in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from trailblazer==20.2.5) (1.12.1)
Requirement already satisfied: coloredlogs in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from trailblazer==20.2.5) (15.0.1)
Requirement already satisfied: marshmallow in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from trailblazer==20.2.5) (3.20.1)
Requirement already satisfied: requests in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from trailblazer==20.2.5) (2.31.0)
Requirement already satisfied: ruamel.yaml in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from trailblazer==20.2.5) (0.18.5)
Requirement already satisfied: tabulate in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from trailblazer==20.2.5) (0.9.0)
Requirement already satisfied: Flask-CORS in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from trailblazer==20.2.5) (4.0.0)
Requirement already satisfied: Flask-Reverse-Proxy in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from trailblazer==20.2.5) (0.2.0.2)
Requirement already satisfied: Flask in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from trailblazer==20.2.5) (3.0.0)
Requirement already satisfied: google-auth in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from trailblazer==20.2.5) (2.23.4)
Requirement already satisfied: gunicorn in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from trailblazer==20.2.5) (21.2.0)
Requirement already satisfied: markupsafe in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from trailblazer==20.2.5) (2.1.3)
Requirement already satisfied: cryptography in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from trailblazer==20.2.5) (41.0.5)
Requirement already satisfied: pydantic in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from trailblazer==20.2.5) (2.5.1)
Requirement already satisfied: pymysql in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from trailblazer==20.2.5) (1.1.0)
Requirement already satisfied: Mako in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from alembic->trailblazer==20.2.5) (1.3.0)
Requirement already satisfied: typing-extensions>=4 in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from alembic->trailblazer==20.2.5) (4.8.0)
Requirement already satisfied: greenlet!=0.4.17 in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from SQLAlchemy->trailblazer==20.2.5) (3.0.1)
Requirement already satisfied: humanfriendly>=9.1 in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from coloredlogs->trailblazer==20.2.5) (10.0)
Requirement already satisfied: cffi>=1.12 in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from cryptography->trailblazer==20.2.5) (1.16.0)
Requirement already satisfied: Werkzeug>=3.0.0 in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from Flask->trailblazer==20.2.5) (3.0.1)
Requirement already satisfied: Jinja2>=3.1.2 in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from Flask->trailblazer==20.2.5) (3.1.2)
Requirement already satisfied: itsdangerous>=2.1.2 in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from Flask->trailblazer==20.2.5) (2.1.2)
Requirement already satisfied: blinker>=1.6.2 in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from Flask->trailblazer==20.2.5) (1.7.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from google-auth->trailblazer==20.2.5) (5.3.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from google-auth->trailblazer==20.2.5) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from google-auth->trailblazer==20.2.5) (4.9)
Requirement already satisfied: packaging in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from gunicorn->trailblazer==20.2.5) (23.2)
Requirement already satisfied: annotated-types>=0.4.0 in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from pydantic->trailblazer==20.2.5) (0.6.0)
Requirement already satisfied: pydantic-core==2.14.3 in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from pydantic->trailblazer==20.2.5) (2.14.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from requests->trailblazer==20.2.5) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from requests->trailblazer==20.2.5) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from requests->trailblazer==20.2.5) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from requests->trailblazer==20.2.5) (2023.7.22)
Requirement already satisfied: ruamel.yaml.clib>=0.2.7 in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from ruamel.yaml->trailblazer==20.2.5) (0.2.8)
Requirement already satisfied: pycparser in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from cffi>=1.12->cryptography->trailblazer==20.2.5) (2.21)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/proj/stage/bin/miniconda3/envs/S_trailblazer/lib/python3.11/site-packages (from pyasn1-modules>=0.2.1->google-auth->trailblazer==20.2.5) (0.5.0)
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 10 (delta 8), reused 10 (delta 8), pack-reused 0
Unpacking objects: 100% (10/10), done.
From github.com:Clinical-Genomics/trailblazer
   4debd78..ab021b8  fix-alembic-migration -> origin/fix-alembic-migration
   382b717..4b9cc68  update-slurm-upload-jobs -> origin/update-slurm-upload-jobs
Already on 'fix-alembic-migration'
Your branch is behind 'origin/fix-alembic-migration' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
Updating 4debd78..ab021b8
Fast-forward
 alembic/versions/2024_01_19_bebe0db0c8de_rename_sars_cov_2_to_mutant.py | 41 -----------------------------------------
 1 file changed, 41 deletions(-)
 delete mode 100644 alembic/versions/2024_01_19_bebe0db0c8de_rename_sars_cov_2_to_mutant.py
/home/henrik.stranneheim
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade dc1aadf08b4d -> 2455fd7f51c4, rename_sars-cov-2_to_mutant_2
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
repository is clean
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/henrik.stranneheim
done.
Log deploy... done.
trailblazer, version 20.2.5
```

**Comment by henrikstranneheim** [comment]
Deployed in production:
```
 3 files changed, 8 insertions(+), 8 deletions(-)
 rename alembic/versions/{2024_01_19_bebe0db0c8de_rename_sars_cov_2_to_mutant.py => 2024_01_29_2455fd7f51c4_rename_sars_cov_2_to_mutant_2.py} (79%)
/home/henrik.stranneheim
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade dc1aadf08b4d -> 2455fd7f51c4, rename_sars-cov-2_to_mutant_2
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
repository is clean
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/henrik.stranneheim
done.
Log deploy... done.

```

**Pull request merged**
