### PR TITLE
Upgrade to Python 3.11

### PR DESCRIPTION
**Pull request by seallard**
## Description
This PR upgrades Python to 3.11.

### Fixed
- Upgrade Python in actions and dockerfile
- Use StrEnum

### This [version](https://semver.org/) is a
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by seallard** [comment]
Deployed to vm: views work, fields can be edited.
Deployed to hasta: upgrade Python version in `S_trailblazer`. scan and adding user works

**Review by diitaz93 — APPROVED** [review]
🙌

**Review by henrikstranneheim — APPROVED** [review]
Great!

**Comment by seallard** [comment]
Upgraded in `P_trailblazer` and `S_trailblazer` on Hasta. Deployed to vms.

**Pull request merged**
