### PR TITLE
feat(refactor): Remove jobs function

### PR DESCRIPTION
**Pull request by henrikstranneheim**
## Description

Remove jobs function since it is not used.

### Changed

- Remove jobs function since it is not used.

### How to prepare for test
- [ ] ssh to hasta (depending on type of change)
- [ ] activate stage: `us`
- [ ] request trailblazer-stage on hasta: `paxa`
- [ ] install on stage:
    ```Shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_trailblazer -t trailblazer -b rm_sql_jobs_function -a
    ```
- [ ] ssh to clinical-db (depending on type of change)
- [ ] install on stage:
`bash /home/proj/production/servers/resources/clinical-db.scilifelab.se/update-trailblazer-ui-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [x] See below

### Expected test outcome
- [x] See below
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [x] tests executed by HS
- [x] "Merge and deploy" approved by @Vince-janv 
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by henrikstranneheim** [comment]
### CLI ✅ 
71° [henrik.stranneheim@hasta:~] [S_base] 1m46s $ trailblazer scan
Status in SLURM: acetuna - 271914
         id                                               step     status  time_limit  time_elapsed              started
0   4907282                      BALSAMIC.acetuna.bwa_mem.5.sh  COMPLETED     8:00:00            17  2023-07-08T14:43:41
1   4907286     BALSAMIC.acetuna.picard_CollectHsMetrics.14.sh  COMPLETED    12:00:00             8  2023-07-08T15:20:11
2   4907287         BALSAMIC.acetuna.sambamba_exon_depth.16.sh  COMPLETED     6:00:00            10  2023-07-08T15:20:11
3   4907288           BALSAMIC.acetuna.mosdepth_coverage.17.sh  COMPLETED    12:00:00             1  2023-07-08T15:20:11
4   4907289        BALSAMIC.acetuna.sambamba_panel_depth.15.sh  COMPLETED     2:30:00             4  2023-07-08T15:20:11
5   4907283  BALSAMIC.acetuna.picard_CollectAlignmentSummar...  COMPLETED    12:00:00             8  2023-07-08T15:00:45
6   4907284        BALSAMIC.acetuna.picard_markduplicates.4.sh  COMPLETED     6:00:00            19  2023-07-08T15:00:45
7   4907285  BALSAMIC.acetuna.picard_CollectInsertSizeMetri...  COMPLETED    12:00:00             3  2023-07-08T15:00:45
8   4907281                        BALSAMIC.acetuna.fastp.6.sh  COMPLETED    12:00:00             1  2023-07-08T14:41:47
9   4907279                      BALSAMIC.acetuna.fastqc.11.sh  COMPLETED    12:00:00             4  2023-07-08T14:38:52
10  4907280                    BALSAMIC.acetuna.fastp_umi.7.sh  COMPLETED  1-00:00:00             2  2023-07-08T14:38:52
11  4907278                      BALSAMIC.acetuna.fastqc.10.sh  COMPLETED    12:00:00             3  2023-07-08T14:38:50
12  4907277                  BALSAMIC.acetuna.concatenate.9.sh  COMPLETED       30:00             0  2023-07-08T14:38:48
13  4907276                  BALSAMIC.acetuna.concatenate.8.sh  COMPLETED       30:00             0  2023-07-08T14:38:45
14  4907291                      BALSAMIC.acetuna.multiqc.2.sh    PENDING       15:00             0                  NaN
15  4907292    BALSAMIC.acetuna.collect_custom_qc_metrics.1.sh    PENDING       15:00             0                  NaN
16  4907293                          BALSAMIC.acetuna.all.0.sh    PENDING       15:00             0                  NaN
17  4907290               BALSAMIC.acetuna.mergeBam_tumor.3.sh    RUNNING  1-06:00:00            23  2023-07-08T15:20:11
Updated status acetuna - 271914: running
Status in SLURM: uphippo - 271913
```
```

### API ✅ 
Screenshot 2023-07-08 at 15 43 22

**Review by Vince-janv — APPROVED** [review]
🧹

**Review by diitaz93 — APPROVED** [review]
👍

**Comment by henrikstranneheim** [comment]
Deployed to Hasta:
```
Log deploy... done.
trailblazer, version 15.0.2
[henrik.stranneheim@hasta:~] [P_base] 3m45s
```

**Pull request merged**
