### PR TITLE
Remove nuxt application

### PR DESCRIPTION
**Pull request by elevu**
This PR reverts to the merge that removed the Nuxt application

### How to prepare for test
- [x] ssh to clinical-db (depending on type of change)
- [x] activate stage: `us`
- [x] request trailblazer-stage on hasta: `paxa`
- [x] install on stage:
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-trailblazer-stage.sh Remove-nuxt-application`

### Expected test outcome
- [x] the installation on clinical-db should proceed without errors
- [x] Take a screenshot and attach or copy/paste the output.

update-trailblazer-ui-stage.sh file without the yarn part
Screen Shot 2020-10-21 at 10 08 41

Successful installation of this branch:
Screen Shot 2020-10-21 at 10 09 33

## Review
- [ ] code approved by
- [x] tests executed by EM
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by elevu** [comment]
Waiting for the servers PR to be deployed before testing and merging this one!

**Comment by elevu** [comment]
Tested with screenshots, ready for review!

**Review by henrikstranneheim — APPROVED** [review]
👍

**Comment by elevu** [comment]
Merged, could someone bump version? Thank you :)

**Comment by henrikstranneheim** [comment]
I can do it

**Comment by henrikstranneheim** [comment]
Hmm, bumpversion is giving me trouble 
```
fatal: tag '8.1.2' already exists
Traceback (most recent call last):
  File "/home/proj/bin/conda/bin/bumpversion", line 11, in <module>
    sys.exit(main())
  File "/home/proj/bin/conda/lib/python3.7/site-packages/bumpversion/__init__.py", line 1004, in main
    vcs.tag(tag_name)
  File "/home/proj/bin/conda/lib/python3.7/site-packages/bumpversion/__init__.py", line 150, in tag
    subprocess.check_output(["git", "tag", name])
  File "/home/proj/bin/conda/lib/python3.7/subprocess.py", line 389, in check_output
    **kwargs).stdout
  File "/home/proj/bin/conda/lib/python3.7/subprocess.py", line 481, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'tag', '8.1.2']' returned non-zero exit status 128.
```
Probalby has to do with the revert previously. Maybe I also need to remove the tag on git? Otherwise I guess I can bump the `.bumpversion.cfg` and `setup.py` manually

**Comment by henrikstranneheim** [comment]
@Mropat Do you know?

**Comment by henrikstranneheim** [comment]
Ok, I just updated the bumpversion and setup.py manually and pushed again. I think we are back to 8.1.2 again (hopefully in all aspects). I thnk next time we should just move forward to the next version patch and not move actual version backwards

**Comment by elevu** [comment]
👍  deployed to prod!

**Pull request merged**
