### PR TITLE
Refactor sql user

### PR DESCRIPTION
**Pull request by henrikstranneheim**
## Description

Refactor sql user

### Added

- `add-user` CLI command
- `get-user` CLI command
- `get-users` CLI command
- Tests

### Changed

- Split CLI function users into two new CLI commands
- Refactored function `user` and moved it to ReadHandler

### How to prepare for test
- [ ] ssh to hasta (depending on type of change)
- [ ] activate stage: `us`
- [ ] request trailblazer-stage on hasta: `paxa`
- [ ] install on stage:
    ```Shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_trailblazer -t trailblazer -b refactor_sql_user -a
    ```
- [ ] ssh to clinical-db (depending on type of change)
- [ ] install on stage:
`bash /home/proj/production/servers/resources/clinical-db.scilifelab.se/update-trailblazer-ui-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [x] See below

### Expected test outcome
- [x] See below
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [x] tests executed by HS
- [x] "Merge and deploy" approved by @diitaz93 
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [x] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by henrikstranneheim** [comment]
### CLII ✅ 
```
θ67° [henrik.stranneheim@hasta:~] [S_base] 16s $ trailblazer add-user test_2.testsson@delete_me.com --name "test_2 Testsson"
User with email test_2.testsson@delete_me.com not found
New user added: test_2.testsson@delete_me.com (62)

θ65° [henrik.stranneheim@hasta:~] [S_base] 17s $ trailblazer add-user test_2.testsson@delete_me.com --name "test_2 Testsson"
User with email test_2.testsson@delete_me.com found

62° [henrik.stranneheim@hasta:~] [S_base] 14s 2 $ trailblazer get-users --email test_2.testsson@delete_me.com --name "test_2 Testsson"
Listing users in database:
{'created_at': datetime.datetime(2023, 6, 28, 17, 2, 23), 'google_id': None, 'email': 'test_2.testsson@delete_me.com', 'avatar': None, 'name': 'test_2 Testsson', 'id': 62, 'is_archived': False}
θ66° [henrik.stranneheim@hasta:~] [S_base] 14s $ trailblazer get-user test_2.testsson@delete_me.com
User with email test_2.testsson@delete_me.com found
Existing user found: {'is_archived': False, 'avatar': None, 'name': 'test_2 Testsson', 'google_id': None, 'created_at': datetime.datetime(2023, 6, 28, 17, 2, 23), 'id': 62, 'email': 'test_2.testsson@delete_me.com'}
```

**Review by diitaz93 — APPROVED** [review]
Great, that seemed necessary 💯

**Comment by henrikstranneheim** [comment]
### API ✅ 
Screenshot 2023-06-30 at 15 13 13

**Comment by henrikstranneheim** [comment]
Deploy on Hasta.
```
Log deploy... done.
trailblazer, version 15.0.0
⌂28.20 θ66° [henrik.stranneheim@hasta:~] [P_base] 2m19s $
```

**Pull request merged**
