### PR TITLE
feat(refactor): Remove unused function

### PR DESCRIPTION
**Pull request by henrikstranneheim**
## Description
Remove is_latest_analysis_ongoing function as it not used anywhere.

### Changed

- Remove is_latest_analysis_ongoing function as it not used anywhere.

### How to prepare for test
- [ ] ssh to hasta (depending on type of change)
- [ ] activate stage: `us`
- [ ] request trailblazer-stage on hasta: `paxa`
- [ ] install on stage:
    ```Shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_trailblazer -t trailblazer -b remove_is_latest_analysis_ongoing -a
    ```
- [ ] ssh to clinical-db (depending on type of change)
- [ ] install on stage:
`bash /home/proj/production/servers/resources/clinical-db.scilifelab.se/update-trailblazer-ui-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [ ] login to ...
- [ ] do ...

### Expected test outcome
- [ ] check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by ChrOertlin — APPROVED** [review]
👍

**Review by Vince-janv — APPROVED** [review]
🪓

**Comment by henrikstranneheim** [comment]
### CLI ✅ 

```
θ73° [henrik.stranneheim@hasta:~] [S_base] 1m48s $ trailblazer ls
272007 | richurchin 2023-08-24 [WGS/QC]
272004 | truepigeon 2023-08-22 [WTS/FAILED]
272001 | cuddlyhen 2023-08-17 [WTS/FAILED]
271975 | ampleray 2023-07-25 [WTS/COMPLETED] - None
271971 | acetuna 2023-07-24 [TGS/COMPLETED] - None
271970 | uphippo 2023-07-24 [TGS/FAILED]
271969 | equalbug 2023-07-24 [TGS/FAILED]
271968 | unitedbeagle 2023-07-24 [TGS/COMPLETED] - None
271967 | setamoeba 2023-07-24 [TGS/COMPLETED] - None
271966 | fleetjay 2023-07-24 [WGS/FAILED]
271965 | civilsole 2023-07-24 [WGS/FAILED]
271957 | uphippo_rsync 2023-07-17 [OTHER/FAILED]
271955 | setamoeba_rsync 2023-07-17 [OTHER/FAILED]
271907 | equalbug_rsync 2023-07-07 [OTHER/FAILED]
271906 | equalbug_rsync 2023-07-07 [OTHER/FAILED]
271905 | equalbug_rsync 2023-07-07 [OTHER/FAILED]
271904 | H27CLDRX3 2023-06-30 [OTHER/COMPLETED] - None
271903 | intentcorgi 2023-06-27 [WGS/COMPLETED] - None
271902 | sharpwhale 2023-06-26 [WGS/COMPLETED] - None
271901 | safeguinea 2023-06-26 [WGS/COMPLETED] - None
271900 | onemite 2023-06-26 [WGS/COMPLETED] - None
271899 | brightcaiman 2023-06-26 [WGS/COMPLETED] - None
271897 | tenderoriole 2023-06-22 [TGS/COMPLETED] - None
271896 | strongbison 2023-06-22 [WES/COMPLETED] - None
271894 | sharppigeon 2023-06-22 [WGS/COMPLETED] - None
271892 | proudcougar 2023-06-22 [WGS/COMPLETED] - None
271890 | nextjackal 2023-06-22 [WGS/COMPLETED] - None
271889 | modernmule 2023-06-22 [WGS/COMPLETED] - None
271888 | intentmayfly 2023-06-22 [WGS/COMPLETED] - None
271887 | kindcaiman 2023-06-22 [WGS/COMPLETED] - None
```

**Comment by henrikstranneheim** [comment]
Deployed in production:
```
Log deploy... done.
trailblazer, version 17.0.3
```

**Pull request merged**
