### PR TITLE
Add user abbreviations to the database

### PR DESCRIPTION
**Pull request by islean**
## Description

This PR attempts to remedy https://github.com/Clinical-Genomics/cigrid-ui/issues/600 although a PR in cigrid-ui will be needed as well as a script. Essentially this PR adds a field to the User table to store the abbreviation of the CG employees to visualize in the FE

### Added

- User.abbreviation column

### How to prepare for test
- [ ] ssh to hasta (depending on type of change)
- [ ] activate stage: `us`
- [ ] request trailblazer-stage on hasta: `paxa`
- [ ] install on stage:
    ```Shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_trailblazer -t trailblazer -b add-user-abbreviations -a
    ```
- [ ] ssh to clinical-db (depending on type of change)
- [ ] install on stage:
`bash /home/proj/production/servers/resources/clinical-db.scilifelab.se/update-trailblazer-ui-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [ ] login to ...
- [ ] do ...

### Expected test outcome
- [ ] check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by islean** [comment]
Alembic upgrade works well and adds the following column to the User table:

image

Downgrade also works.

**Review by henrikstranneheim — COMMENTED** [review]
Nice! Should we also add a means of adding/updating an abbreviation to new/existing users?

**Comment by islean** [comment]
Spoke with KSV and the current suggesting is to add a flag for setting it in `trailblazer add user` and let updates be a manual thing since the goal is for the abbreviations to be constant.

**Comment by seallard** [comment]
Duplicate https://github.com/Clinical-Genomics/trailblazer/pull/462

**Pull request closed without merging**
