### PR TITLE
Move trailblazer queries

### PR DESCRIPTION
**Pull request by Mropat**
- Moves Trailblazer queries from TrailblazerAPI to Trailblazer BaseHandler (some will be redundant to maintain compatibility with CG)
- Change black hook arg to be consistent with rest of cg
- Add pyproject.toml file
- Remove precommit as dev requirement

### How to prepare for test
- [x] ssh to hasta (depending on type of change)
- [x] activate stage: `us`
- [x] request trailblazer-stage on hasta: `paxa`
- [x] install on stage:
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-trailblazer-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [x] login to hasta 
- [x] do up
- [x] install cg on branch  feat/detach-tb-2-1
- [x] do cg workflow mip-dna -c keenviper

### Expected test outcome
- [x] No broken imports or requirements
- [x] Case starts successfully and is tracked by Trailblazer on stage

## Review
- [x] code approved by AJ, HS
- [x] tests executed by MR
- [x] "Merge and deploy" approved by MR
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by Mropat** [comment]
@henrikstranneheim @jemten 
Can someone check/approve the code? 
The travis/deployment problems are not related to these changes and should go away when @elevu has finalized the modernization!

**Review by jemten — APPROVED** [review]
👍

**Review by henrikstranneheim — APPROVED** [review]
looks good!

**Comment by Mropat** [comment]
Installed on stage
image

Installed on prod
image

**Pull request merged**
