### PR TITLE
Remove Config from Trailblazer API

### PR DESCRIPTION
**Pull request by Mropat**
#### This PR removes:

- ConfigHandler, as well as tests and exceptions related to the class
- The tests and exceptions have been moved to cg codebase

### How to prepare for test
- [x] ssh to hasta
- [x] activate stage: `us`
- [x] request trailblazer-stage on hasta: `paxa`
- [x] install on stage:
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-trailblazer-stage.sh feat/remove-confighandler`

### How to test
- This will be tested in the cg PR linked below

## Review
- [x] code approved by HS
- [x] tests executed by MR
- [x] "Merge and deploy" approved by HS
Thanks for filling in who performed the code review and the test!

## Implementation ##
- [x] Together with https://github.com/Clinical-Genomics/cg/pull/730

## AM update
- [x] Updated AM doc 1383; Removed trailblazer start reference

### This [version](https://semver.org/) is a
- [x] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by henrikstranneheim — APPROVED** [review]
👍

**Comment by henrikstranneheim** [comment]
@Mropat Did you black the files?

**Comment by Mropat** [comment]
> @Mropat Did you black the files?
I did but Black isnt happy anyway

**Comment by henrikstranneheim** [comment]
Did you use the latest stable version e.g. like in the .pre-commit

**Review by jemten — APPROVED** [review]
👍

**Comment by Mropat** [comment]
Proof CG does not break with this PR
image

**Review by henrikstranneheim — APPROVED** [review]
👍

**Comment by henrikstranneheim** [comment]
@Mropat Shall I merge this one?

@emmser @karlnyr @henningonsbring @talnor @b4ckm4n This will remove trailblazer start from the CLI, as cg has completely taken over this functionality from TB.  I have updated AM 1383 accordingly.

**Review by jemten — APPROVED** [review]

**Comment by Mropat** [comment]
Upload did not break from this!
:+1: to merge!

**Comment by Mropat** [comment]
stage install
image

**Comment by Mropat** [comment]
prod install
image

**Pull request merged**
