### PR TITLE
Remove nuxt application

### PR DESCRIPTION
**Pull request by elevu**
This PR remove all the configuration related to the Trailblazer Nuxt frontend application which moved to Firebase
Is is related to this task: Clinical-Genomics/trailblazer#118
Before this PR is merged, we need to have the scilifelab DNS point to the new Trailblazer-UI IPs.

### How to prepare for test
- [ ] ssh to hasta (depending on type of change)
- [ ] activate stage: `us`
- [ ] request trailblazer-stage on hasta: `paxa`
- [ ] install on stage:
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-trailblazer-stage.sh Remove-nuxt-application`

### Expected test outcome
- [ ] the installation and functionality of trailblazer-api should work as usual

## Review
- [ ] code approved by
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by henrikstranneheim — APPROVED** [review]
Oh, that is  a lot of old code disappearing, 😄

**Comment by elevu** [comment]
Merged, the Nuxt app is not available anymore, the server PR can be addressed separately, we don't need to wait for that to be merged.

**Comment by henrikstranneheim** [comment]
Do we need to deploy anything or bumpversion etc?

**Comment by elevu** [comment]
No need to deploy anything, nothing was touched on the Python side and the deployment hasta script doesn't include the Nuxt app. Bumpversion depends on your preferences, I would say it is a different version!

**Comment by henrikstranneheim** [comment]
Will bump a patch

**Comment by henrikstranneheim** [comment]
Done. Nice work!

**Pull request merged**
