### PR TITLE
fix(round_error): #254

### PR DESCRIPTION
**Pull request by henrikstranneheim**
## Description

Fix incorrectly setting analysis status as canceled due to rounding to 0.

### Fixed

- Fix incorrectly setting analysis status as canceled due to rounding to 0. #254 

### How to prepare for test
- [ ] ssh to hasta (depending on type of change)
- [ ] activate stage: `us`
- [ ] request trailblazer-stage on hasta: `paxa`
- [ ] install on stage:
    ```Shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_trailblazer -t trailblazer -b fix_wrong_tb_status -a
    ```
- [ ] ssh to clinical-db (depending on type of change)
- [ ] install on stage:
`bash /home/proj/production/servers/resources/clinical-db.scilifelab.se/update-trailblazer-ui-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [ ] login to ...
- [ ] do ...

### Expected test outcome
- [ ] check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by fevac — APPROVED** [review]
Nice! 🌟 looks good

**Comment by fevac** [comment]
has this been tested? does it fix the issue?

**Comment by henrikstranneheim** [comment]
Recreating it in the tests solved it and the bug is logical. Hard to test in real life but I will just check the code works on stage before merging

**Comment by henrikstranneheim** [comment]
### CLI ✅ 
```
Action running set for case justhusky
mip-dna run started!
θ61° [henrik.stranneheim@hasta:~] [S_base] 1m44s $ trailblazer scan
Status in SLURM: justhusky - 272006
Updated status justhusky - 272006: running
slurm_load_jobs error: Invalid job id specified
Error updating analysis for: case - HYG7YDSXX : CalledProcessError
Error updating analysis for: case - gentleamoeba : FileNotFoundError
Error updating analysis for: case - masterimpala : FileNotFoundError
Error updating analysis for: case - starakita : FileNotFoundError
Error updating analysis for: case - goodrodent : FileNotFoundError
Error updating analysis for: case - strongbug : FileNotFoundError
Error updating analysis for: case - masterwombat : FileNotFoundError
Error updating analysis for: case - warmcalf : FileNotFoundError
Error updating analysis for: case - jointstag : FileNotFoundError
Error updating analysis for: case - finerobin : FileNotFoundError
Error updating analysis for: case - wantedhen : FileNotFoundError
Error updating analysis for: case - cleanleech : PermissionError
Error updating analysis for: case - socialearwig : FileNotFoundError
Error updating analysis for: case - topsdodo : FileNotFoundError
Error updating analysis for: case - usablefeline : PermissionError
Error updating analysis for: case - 233471 : FileNotFoundError
Error updating analysis for: case - crispshiner : FileNotFoundError
Error updating analysis for: case - supertiger : PermissionError
Error updating analysis for: case - fullfrog : FileNotFoundError
Error updating analysis for: case - toplouse : FileNotFoundError
Error updating analysis for: case - sunnycondor : FileNotFoundError
Error updating analysis for: case - keyeft : FileNotFoundError
Error updating analysis for: case - robustalien : PermissionError
Error updating analysis for: case - busyowl : PermissionError
Error updating analysis for: case - boldhound : PermissionError
Error updating analysis for: case - vastboar : FileNotFoundError
Error updating analysis for: case - topsworm : PermissionError
Error updating analysis for: case - setcolt : PermissionError
Error updating analysis for: case - proudfish : PermissionError
Error updating analysis for: case - funnyaphid : FileNotFoundError
Error updating analysis for: case - onestag : PermissionError
Error updating analysis for: case - newgopher : PermissionError
Error updating analysis for: case - helpedlab : MissingSqueueOutput
Error updating analysis for: case - goodbengal : MissingSqueueOutput
Error updating analysis for: case - grandaphid : PermissionError
All analyses updated!
```

### API ✅ 
Screenshot 2023-08-23 at 12 18 48

**Comment by henrikstranneheim** [comment]
Deployed in produuction:
```
Log deploy... done.
trailblazer, version 16.0.4
[henrik.stranneheim@hasta:~] [P_base] 1m20s $
```

**Pull request merged**
